apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: o50a3sq1f-java-springboot
  janus-idp.io/tekton: o50a3sq1f-java-springboot
  backstage.io/kubernetes-id: o50a3sq1f-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: o50a3sq1f-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
